server:
  port: 0
spring:
  application:
    name: users-service
  devtools:
    restart:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
