server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}


eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka