server:
  port: 8010
spring:
  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true